// Code generated by goctl. DO NOT EDIT.
package types

type CreateRequest struct {
	Uid    uint64 `json:"uid"`
	Pid    uint64 `json:"pid"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type CreateResponse struct {
	Id uint64 `json:"id"`
}

type UpdateRequest struct {
	Id     uint64 `json:"id"`
	Uid    uint64 `json:"uid"`
	Pid    uint64 `json:"pid"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type UpdateResponse struct {
}

type RemoveRequest struct {
	Id uint64 `json:"id"`
}

type RemoveResponse struct {
}

type DetailRequest struct {
	Id uint64 `json:"id"`
}

type DetailResponse struct {
	Id     uint64 `json:"id"`
	Uid    uint64 `json:"uid"`
	Pid    uint64 `json:"pid"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type ListRequest struct {
	Uid uint64 `json:"uid"`
}

type OrderResponse struct {
	Id     uint64 `json:"id"`
	Uid    uint64 `json:"uid"`
	Pid    uint64 `json:"pid"`
	Amount uint64 `json:"amount"`
	Status uint64 `json:"status"`
}

type OrdersResponse struct {
	Orders []*OrderResponse `json:"orders"`
}
